apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-service
  description: A Python service that dsplays time

  annotations:
    github.com/project-slug: c2r79/python-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
