site_name:  'python-service'
site_description: 'Main documentation for our Python service'
repo_url: https://github.com/c2r79/python-service
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Introduction:
    - Getting started: 'index.md'