apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-service.fullname" . }}
  labels:
    {{- include "python-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000 #http
      protocol: TCP
      name: http
  selector:
    {{- include "python-service.selectorLabels" . | nindent 4 }}
