redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  imagePullSecrets:
    - name: regcred

repoServer:
  replicas: 1
  imagePullSecrets:
    - name: regcred

applicationSet:
  replicas: 1

global:
  domain: argocd.los.com

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true
    hosts:
      - python-service.app
    tlsSecretName: python-service-tls